#!/bin/bash

export PATH="$HOME/.local/bin:$PATH"

export LESSCHARSET=utf-8        # show Chinese normal in git log
export TMOUT=864000
export PS1='[\u@\H \w]'

ulimit -c unlimited
ulimit -s 16777216

shopt -s expand_aliases

alias gits="git status"
alias git_push_branch="git branch | grep '*' | head -n1 | cut -d' ' -f2 | xargs -i git push origin HEAD:refs/for/{}"

alias gdb="$HOME/.local/gdb-12.1/bin/gdb"

alias shttp="hostname -i; python3 -m http.server 8989"

export FZF_DEFAULT_COMMAND="ag --color -l -g -p $HOME/.local/ag_ignore -S -U \"\""
